TrajectoryPlannerROS:
  max_vel_x: 0.9
  min_vel_x: 0.4
  max_vel_theta: 3.14
  min_in_place_vel_theta: 1.5
  backup_vel: -0.4
  escape_vel: -0.4

  acc_lim_theta: 12
  acc_lim_x: 2.5

  holonomic_robot: false
