# http://wiki.ros.org/navigation/Tutorials/RobotSetup
obstacle_range: 3.0
raytrace_range: 3.0
footprint: [[0.14, 0.12], [-0.14, 0.12],[-0.14, -0.12],[0.14, -0.12]]
#robot_radius: ir_of_robot
inflation_radius: 0.15

observation_sources: laser_scan_sensor #point_cloud_sensor

laser_scan_sensor: {sensor_frame: frame_name, data_type: LaserScan, topic: topic_name, marking: true, clearing: true}
#point_cloud_sensor: {sensor_frame: front_camera_frame, data_type: PointCloud, topic: /front_camera/front_camera/convert/final_points, marking: true, clearing: true}
