obstacle_range: 2.5
raytrace_range: 3.0
# Obstacle Cost Shaping (http://wiki.ros.org/costmap_2d/hydro/inflation)
# robot_radius: 0.20  # distance a circular robot should be clear of the obstacle (kobuki: 0.18)
footprint: [[0.23, 0.18], [-0.23, 0.18],[-0.23, -0.18],[0.23, -0.18]]  # if the robot is not circular
#robot_radius: ir_of_robot
inflation_radius: 0.55

observation_sources:
