obstacle_range: 2.5
raytrace_range: 3.0
# Obstacle Cost Shaping (http://wiki.ros.org/costmap_2d/hydro/inflation)
# robot_radius: 0.20  # distance a circular robot should be clear of the obstacle (kobuki: 0.18)
footprint: [[0.14, 0.12], [-0.14, 0.12],[-0.14, -0.12],[0.14, -0.12]]  # if the robot is not circular
#robot_radius: ir_of_robot
inflation_radius: 0.01

observation_sources: laser_scan_sensor

laser_scan_sensor: {sensor_frame: frame_name, data_type: LaserScan, topic: topic_name, marking: true, clearing: true}
