# The joint state controller handles publishing transforms for any moving joints

joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

#left_front_joint_velocity_controller:
#  type: effort_controllers/JointVelocityController
#  joint: left_front_wheel_joint
#  pid: {p: 0.001, i: 0.0, d: 0.0}
#
#left_back_joint_velocity_controller:
#  type: effort_controllers/JointVelocityController
#  joint: left_back_wheel_joint
#  pid: {p: 0.001, i: 0.0, d: 0.0}
#
#right_front_joint_velocity_controller:
#  type: effort_controllers/JointVelocityController
#  joint: right_front_wheel_joint
#  pid: {p: 0.001, i: 0.0, d: 0.0}
#
#right_back_joint_velocity_controller:
#  type: effort_controllers/JointVelocityController
#  joint: right_back_wheel_joint
#  pid: {p: 0.001, i: 0.0, d: 0.0}
