# Move base node parameters. For full documentation of the parameters in this file, please see
#
#  http://www.ros.org/wiki/move_base
#

base_global_planner: "global_planner/GlobalPlanner" #alternatives: global_planner/GlobalPlanner, carrot_planner/CarrotPlanner
#base_local_planner: #"teb?"
#recovery_behaviors:
  #- name: 'super_conservative_reset1'
  #type: 'clear_costmap_recovery/ClearCostmapRecovery'
  #- name: 'conservative_reset1'
  #type: 'clear_costmap_recovery/ClearCostmapRecovery'
  #- name: 'aggressive_reset1'
  #type: 'clear_costmap_recovery/ClearCostmapRecovery'
  #- name: 'clearing_rotation1'
  #type: 'rotate_recovery/RotateRecovery'
  #- name: 'super_conservative_reset2'
  #type: 'clear_costmap_recovery/ClearCostmapRecovery'
  #- name: 'conservative_reset2'
  #type: 'clear_costmap_recovery/ClearCostmapRecovery'
  #- name: 'aggressive_reset2'
  #type: 'clear_costmap_recovery/ClearCostmapRecovery'
  #- name: 'clearing_rotation2'
  #type: 'rotate_recovery/RotateRecovery'
controller_frequency: 30.0 # 20
planner_patience: 1.0 # 5.0
controller_patience: 3.0 # 15
conservative_reset_dist: 1 # 3.0
#recovery_behavior_enabled: true
clearing_rotation_allowed: false # true
shutdown_costmaps: false # true
oscillation_timeout: 3.0 #0 = infinite
oscillation_distance: 0.5 #.5
#planner_frequency: 0
#max_planning_retries: -1
