TebLocalPlannerROS:

  # Misc
  odom_topic: robot_diff_drive_controller/odom
  map_frame: /map


  # Robot Kinematics
  acc_lim_x: .75
  max_vel_x: 1.5
  max_vel_x_backwards: 1.5
  acc_lim_theta: 3.14
  max_vel_theta: 6.28 # ~about 2 seconds for a full turn
  min_turning_radius: 0.0
  wheelbase: .2 # The distance between the rear axle and the front axle.
  cmd_angle_instead_rotvel: False
  # max_vel_y: 0
  # acc_lim_y: .5
  footprint_model: # types: "point", "circular", "two_circles", "line", "polygon"
    type: "circular"
    radius: 0.19 # for type "circular"
    verties: [[0.14, 0.12], [-0.14, 0.12],[-0.14, -0.12],[0.14, -0.12]]
  # is_footprint_dynamic: false


  # Goal Tolerance
  xy_goal_tolerance: .05 # 0.2
  yaw_goal_tolerance: .05 # .2
  free_goal_vel: False # Remove the goal velocity constraint such that the robot can arrive at the goal with maximum speed


  # Trajectory Configuration
  dt_ref: 0.3
  dt_hysteresis: 0.1
  global_plan_overwrite_orientation: True
  max_global_plan_lookahead_dist: .5 # ~2 feet # Specify the maximum length (cumulative Euclidean distances) of the subset of the global plan taken into account for optimization. The actual length is than determined by the logical conjunction of the local costmap size and this maximum bound.
  # force_reinit_new_goal_dist: 1
  # feasibility_check_no_poses: 4
  # publish_feedback: False
  shrink_horizon_backup: False
  # allow_init_with_backwards_motion: False
  exact_arc_length: False # If true, the planner uses the exact arc length in velocity, acceleration and turning rate computations (-> increased cpu time), otherwise the Euclidean approximation is used.
  # shrink_horizon_min_duration: 10


  # Obstacles
  min_obstacle_dist: 0.05
  include_costmap_obstacles: False
  # costmap_obstacles_behind_robot_dist: 1.0
  obstacle_poses_affected: 30
  inflation_dist: 0.0 # Buffer zone around obstacles with non-zero penalty costs (should be larger than min_obstacle_dist in order to take effect).
  include_dynamic_obstacles: True
  # legacy_obstacle_association: False
  # obstacle_association_force_inclusion_factor: 1.5
  # obstacle_association_cutoff_factor: 5
  # costmap_converter_plugin: ""
  # costmap_converter_spin_thread: True
  # costmap_converter_rate: 5


  # Optimization
  no_inner_iterations: 10
  no_outer_iterations: 5
  optimization_activate: True
  optimization_verbose: False
  penalty_epsilon: 0.1
  ## weight_viapoint: 0
  weight_max_vel_x: 2 # 2
  weight_max_vel_theta: 1 # 1
  #weight_acc_lim_x: 1
  #weight_acc_lim_theta: 1
  #weight_kinematics_nh: 1000 # non holonomic
  weight_kinematics_forward_drive: 100
  #weight_kinematics_turning_radius: 1 #only used for car robots
  #weight_optimaltime: 1
  #weight_obstacle: 50
  ## weight_viapoint: 1
  #weight_inflation: .1
  ## weight_adapt_factor: 2
  #weight_dynamic_obstacle: 100


  # Parallel Planning in distinctive Topologies
  enable_homotopy_class_planning: True # Activate parallel planning in distinctive topologies (requires much more CPU resources, since multiple trajectories are optimized at once)
  enable_multithreading: True
  max_number_classes: 4
  # selection_cost_hysteresis: 1
  # selection_obst_cost_scale: 100
  # selection_viapoint_cost_scale: 1
  # selection_alternative_time_cost: false
  # roadmap_graph_no_samples: 15
  roadmap_graph_area_width: 2 #6
  h_signature_prescaler: 0.7 #1
  h_signature_threshold: 0.1 #.1
  obstacle_heading_threshold: 0.45 #1
  visualize_hc_graph: True
  # viapoints_all_candidates: true
  # switching_blocking_period: 0


  # Not Used
  # simple_exploration: False
  # obstacle_keypoint_offset: 0.1
  # teb_autosize: True

