TebLocalPlannerROS:

  odom_topic: odom
  map_frame: /map

    # Trajectory

  teb_autosize: True
  dt_ref: 0.3
  dt_hysteresis: 0.1
  global_plan_overwrite_orientation: True
  max_global_plan_lookahead_dist: .5 # ~2 feet
  feasibility_check_no_poses: 20
  exact_arc_length: False
  allow_init_with_backwards_motion: True

    # Robot

  max_vel_x: 1.5
  max_vel_x_backwards: 1.5
  # ~about 2 seconds for a full turn
  max_vel_theta: 6.28
  acc_lim_x: 3
  acc_lim_theta: 12.56
  min_turning_radius: 0.01
  footprint_model: # types: "point", "circular", "two_circles", "line", "polygon"
    type: "two_circles"
    radius: 0.9 # for type "circular"
    line_start: [-0.3, 0.0] # for type "line"
    line_end: [0.3, 0.0] # for type "line"
    front_offset: 0.07 # for type "two_circles"
    front_radius: 0.15 # for type "two_circles"
    rear_offset: 0.09 # for type "two_circles"
    rear_radius: 0.178 # for type "two_circles"
    vertices: [ [0.25, -0.05], [0.18, -0.05], [0.18, -0.18], [-0.19, -0.18], [-0.25, 0], [-0.19, 0.18], [0.18, 0.18], [0.18, 0.05], [0.25, 0.05] ] # for type "polygon"

      # GoalTolerance

  xy_goal_tolerance: 0.01
  yaw_goal_tolerance: 0.1
  # super cool
  free_goal_vel: False

  # Obstacles
  min_obstacle_dist: 0.1
  inflation_dist: 0.2
  include_costmap_obstacles: False
  costmap_obstacles_behind_robot_dist: 1.0
  obstacle_poses_affected: 30
    # costmap_converter_plugin: ""
    # costmap_converter_spin_thread: True
    # costmap_converter_rate: 5

    # Optimization

  no_inner_iterations: 5
  no_outer_iterations: 4
  optimization_activate: True
  optimization_verbose: False
  penalty_epsilon: 0.1
  # weight_viapoint: 0
  weight_max_vel_x: 1.5
  weight_max_vel_theta: 6.28
  weight_acc_lim_x: 3
  weight_acc_lim_theta: 12.56
  weight_kinematics_nh: 1000
  weight_kinematics_forward_drive: 0.01
  weight_kinematics_turning_radius: 0.01
  weight_optimaltime: 1.5
  weight_obstacle: 100
  weight_dynamic_obstacle: 100 # not in use yet

  # Homotopy Class Planner
  visualize_hc_graph: True
  enable_homotopy_class_planning: True
  enable_multithreading: True
  simple_exploration: False
  selection_cost_hysteresis: 1.4
  selection_alternative_time_cost: true # not in use yet
  max_number_classes: 5
  roadmap_graph_no_samples: 15
  roadmap_graph_area_width: 2
  h_signature_prescaler: 0.7
  h_signature_threshold: 0.1
  obstacle_keypoint_offset: 0.1
  obstacle_heading_threshold: 0.45
